# Generated by Django 5.2.12 on 2026-03-31 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Recipient or Service Name", max_length=150
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("due_date", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Housing", "Housing"),
                            ("Utilities", "Utilities"),
                            ("Grocery", "Grocery"),
                            ("Transportation", "Transportation"),
                            ("Healthcare", "Healthcare"),
                            ("Entertainment", "Entertainment"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=50,
                    ),
                ),
                (
                    "expense_type",
                    models.CharField(
                        choices=[
                            ("One-Time", "One-Time Payment"),
                            ("Subscription", "Recurring Subscription"),
                            ("Bill", "Monthly Bill"),
                        ],
                        default="One-Time",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Paid", "Paid"), ("Pending", "Pending")],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("is_autopay", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
