# Generated by Django 5.2.12 on 2026-03-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Vault", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="is_cc_bill",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="expense",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Credit Card", "Credit Card"),
                    ("Debit Card", "Debit Card"),
                    ("Cash", "Cash"),
                    ("None", "Not Applicable / Pending"),
                ],
                default="None",
                max_length=20,
            ),
        ),
    ]
