# Generated by Django 5.2.12 on 2026-03-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Vault", "0002_expense_is_cc_bill_expense_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("Housing", "Housing"),
                    ("Utilities", "Utilities"),
                    ("Grocery", "Grocery"),
                    ("Transportation", "Transportation"),
                    ("Healthcare", "Healthcare"),
                    ("Entertainment", "Entertainment"),
                    ("Credit Card", "Credit Card"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=50,
            ),
        ),
    ]
