# Generated by Django 5.2.12 on 2026-03-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Vault", "0003_alter_expense_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="month",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="expense",
            name="week",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="expense",
            name="year",
            field=models.IntegerField(default=2026),
        ),
    ]
