# Generated by Django 5.2.12 on 2026-04-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Vault", "0008_savingsgoal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("Housing", "Housing"),
                    ("Utilities", "Utilities"),
                    ("Grocery", "Grocery"),
                    ("Food", "Food"),
                    ("Transportation", "Transportation"),
                    ("Healthcare", "Healthcare"),
                    ("Entertainment", "Entertainment"),
                    ("Credit Card", "Credit Card"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=50,
            ),
        ),
    ]
